# Generated by Django 5.2.4 on 2025-07-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nik', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('lapdik_number', models.CharField(blank=True, max_length=30)),
                ('birth_place', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('school_origin', models.CharField(blank=True, max_length=120)),
                ('citizenship_status', models.CharField(blank=True, max_length=50)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=20)),
                ('region_origin', models.CharField(blank=True, max_length=80)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('institution', models.CharField(blank=True, max_length=120)),
                ('faculty', models.CharField(blank=True, max_length=120)),
                ('major', models.CharField(blank=True, max_length=120)),
                ('degree_level', models.CharField(choices=[('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=20)),
                ('semester_level', models.SmallIntegerField()),
                ('latest_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dorm_name', models.CharField(blank=True, max_length=80)),
                ('dorm_location', models.CharField(blank=True, max_length=150)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('umdah_name', models.CharField(blank=True, max_length=80)),
                ('umdah_phone', models.CharField(blank=True, max_length=20)),
                ('education_funding', models.CharField(choices=[('beasiswa', 'Beasiswa'), ('non-beasiswa', 'Non-Beasiswa')], max_length=20)),
                ('scholarship_source', models.CharField(blank=True, max_length=120, null=True)),
                ('living_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('photo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
