# Generated by Django 5.2.4 on 2026-03-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0019_alter_student_degree_level_alter_student_home_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('olahraga', 'Minat Olahraga'), ('seni', 'Minat Seni'), ('literasi', 'Minat Literasi'), ('keilmuan', 'Minat Keilmuan'), ('mtq', 'MTQ'), ('media', 'Media')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kategori Minat',
                'verbose_name_plural': 'Kategori Minat',
                'ordering': ['id'],
            },
        ),

        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama Minat')),
                ('allow_custom', models.BooleanField(default=False, help_text='Centang jika mahasiswa boleh mengisi nilai kustom untuk pilihan ini.', verbose_name='Bisa Isi Sendiri')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='data_management.interestcategory')),
            ],
            options={
                'verbose_name': 'Minat',
                'verbose_name_plural': 'Minat',
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_value', models.CharField(blank=True, max_length=255, verbose_name='Isi Sendiri')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_interests', to='data_management.interest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_interests', to='data_management.student')),
            ],
            options={
                'verbose_name': 'Minat Mahasiswa',
                'verbose_name_plural': 'Minat Mahasiswa',
                'unique_together': {('student', 'interest')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(blank=True, through='data_management.StudentInterest', to='data_management.interest', verbose_name='Minat'),
        ),
    ]
