# Generated by Django 5.2.4 on 2026-03-04 14:17

from django.db import migrations

INTEREST_DATA = [
    ('olahraga', 'Minat Olahraga', [
        ('Sepak Bola', False),
        ('Voli', False),
        ('Futsal', False),
        ('Basket', False),
        ('Badminton', False),
        ('Padel', False),
        ('Isi Sendiri', True),
    ]),
    ('seni', 'Minat Seni', [
        ('Tari Tradisional', False),
        ('Musik', False),
        ('Public Speaking', False),
        ('Lukis dan Kaligrafi', False),
        ('Isi Sendiri', True),
    ]),
    ('literasi', 'Minat Literasi', [
        ('Menulis Sastra', False),
        ('Menulis Karya Ilmiah', False),
        ('Jurnalistik', False),
        ('Membaca dan Berdiskusi', False),
        ('Isi Sendiri', True),
    ]),
    ('keilmuan', 'Minat Keilmuan', [
        ('Mawaris', False),
        ('Ekonomi Syariah', False),
        ('Kajian Tokoh', False),
        ('Kajian Filsafat', False),
        ('Isi Sendiri', True),
    ]),
    ('mtq', 'MTQ', [
        ('Tahfiz', False),
        ('Tilawah', False),
        ('Fahmil', False),
        ('Syarhil', False),
        ('Isi Sendiri', True),
    ]),
    ('media', 'Media', [
        ('Design Grafis', False),
        ('Photography', False),
        ('Editing Videography', False),
        ('Konten Kreator/Talent', False),
        ('Isi Sendiri', True),
    ]),
]


def seed_interests(apps, schema_editor):
    InterestCategory = apps.get_model('data_management', 'InterestCategory')
    Interest = apps.get_model('data_management', 'Interest')

    for slug, name, items in INTEREST_DATA:
        category = InterestCategory.objects.create(slug=slug, name=name)
        for order, (item_name, allow_custom) in enumerate(items, start=1):
            Interest.objects.create(
                category=category,
                name=item_name,
                allow_custom=allow_custom,
                order=order,
            )


def unseed_interests(apps, schema_editor):
    InterestCategory = apps.get_model('data_management', 'InterestCategory')
    InterestCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0020_add_interest_models'),
    ]

    operations = [
        migrations.RunPython(seed_interests, reverse_code=unseed_interests),
    ]
