# Generated by Django 5.2.4 on 2026-03-04 14:19

from django.db import migrations

# Categories that already have "Isi Sendiri"
ALREADY_HAS = {'keilmuan', 'mtq'}


def add_isi_sendiri(apps, schema_editor):
    InterestCategory = apps.get_model('data_management', 'InterestCategory')
    Interest = apps.get_model('data_management', 'Interest')

    for category in InterestCategory.objects.exclude(slug__in=ALREADY_HAS):
        last_order = category.interests.order_by('-order').values_list('order', flat=True).first() or 0
        Interest.objects.get_or_create(
            category=category,
            name='Isi Sendiri',
            defaults={'allow_custom': True, 'order': last_order + 1},
        )


def remove_isi_sendiri(apps, schema_editor):
    InterestCategory = apps.get_model('data_management', 'InterestCategory')
    Interest = apps.get_model('data_management', 'Interest')

    Interest.objects.filter(
        name='Isi Sendiri',
        category__slug__in=['olahraga', 'seni', 'literasi', 'media'],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0021_seed_interest_data'),
    ]

    operations = [
        migrations.RunPython(add_isi_sendiri, reverse_code=remove_isi_sendiri),
    ]
