# Generated by Django 5.2.4 on 2026-03-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0022_add_isi_sendiri_all_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty_custom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fakultas (Isi Sendiri)'),
        ),
        migrations.AddField(
            model_name='student',
            name='institution_custom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Institusi (Isi Sendiri)'),
        ),
        migrations.AddField(
            model_name='student',
            name='major_custom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Jurusan (Isi Sendiri)'),
        ),
        migrations.AddField(
            model_name='student',
            name='membership_status',
            field=models.CharField(blank=True, choices=[('biasa', 'Biasa'), ('luar_biasa', 'Luar Biasa'), ('istimewa', 'Istimewa')], max_length=20, verbose_name='Status Keanggotaan'),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship_source_custom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sumber Beasiswa (Isi Sendiri)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, choices=[('dakwah', 'Dakwah Islamiyyah'), ('dirasat_insaniyyah', 'Dirasat Insaniyyah'), ('dirasat_banat', 'Dirasat Islamiyah wa Arabiyyah Banat'), ('dirasat_banin', 'Dirasat Islamiyah wa Arabiyyah Banin'), ('dirasat_ulya', 'Dirasat Ulya'), ('dirasat_ulum', 'Dirasat Ulum'), ('handasah', 'Handasah'), ('ilam', 'Ilam'), ('ilmu_quran', 'Ilmu Al-Quran'), ('kedokteran', 'Kedokteran'), ('lughah_arabiyyah', 'Lughah Arabiyyah'), ('syariah_qanun', 'Syariah wa Qanun'), ('tarbiyyah', 'Tarbiyyah'), ('tijarah', 'Tijarah'), ('ushuluddin', 'Ushuluddin'), ('other', 'Lainnya (Isi Sendiri)')], max_length=50, verbose_name='Fakultas'),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_location',
            field=models.CharField(blank=True, choices=[('1st_settlement', '1st Settlement'), ('suuq_asyir', 'Suuq Asyir'), ('madrasah_asyir', 'Madrasah Asyir'), ('musallas_asyir', 'Musallas Asyir'), ('gami_asyir', "Gami' Asyir"), ('bawabat_asyir', 'Bawabat Asyir'), ('hafez_badawy_h7', 'Hafez Badawy Hayy 7'), ('abdul_qahir_h7', 'Abdul Qahir Al Gargawy Hayy 7'), ('omar_mokhtar_h7', 'Omar El Mokhtar Hayy 7'), ('farid_abou_hadid_h7', 'Mohamed Farid Abou Hadid Hayy 7'), ('taha_dinary_h7', 'Taha Dinary Hayy 7'), ('shafy_mohammed_h7', 'El Shafy Mohammed Hayy 7'), ('ibrahim_naga_h7', 'Ibrahim Abou El Naga Hayy 7'), ('fateh_allah_h7', 'Fateh Allah refaat Hayy 7'), ('mahdi_baraka_h7', 'Al Mahdi Ibn Baraka Hayy 7'), ('abou_hayan_h7', 'Abou Hayan Al Tawhid Hayy 7'), ('ahmed_zayyad_h7', 'Ahmed Hasan El Zayyad Hayy 7'), ('ismail_zohdy_h7', 'Ismail Zohdy Hayy 7'), ('gamal_shayal_h7', 'Gamal Al Din Al Shayal Hayy 7'), ('dr_nabawy_h7', 'Dr Mohammed Al Nabawy Hayy 7'), ('mohamed_hamid_h7', 'Mohamed Hamid Hayy 7'), ('mohammed_faheem_h7', 'Mohammed Faheem Hayy 7'), ('mohammed_saedy_h7', 'Mohammed El Saedy Hayy 7'), ('taher_gazairy_h7', 'Taher Al Gazairy Hayy 7'), ('abou_ramy_h7', 'Abou Ramy Hayy 7'), ('misr_sudan_h7', 'Misr wa Sudan Hayy 7'), ('awwal_sabea_h7', 'Awwal Sabea Hayy 7'), ('hadiqoh_dauliyyah_h7', 'Hadiqoh Dauliyyah Hayy 7'), ('hayy_tsamin', 'Hayy Tsamin'), ('hayy_tasi', "Hayy Tasi'"), ('gamaliya', 'Gamaliya'), ('khadrawy_darrasah', 'Khadrawy Darrasah'), ('darb_dalil_darrasah', 'Darb Ad Dalil Darrasah'), ('rifai_darrasah', "Rifa'i Darrasah"), ('juwaini_darrasah', 'Juwaini Darrasah'), ('aslan_darrasah', 'Aslan Darrasah'), ('sayyidah_fathimah_darrasah', 'Sayyidah Fathimah Darrasah'), ('tanbugho_darrasah', 'Tanbugho Darrasah'), ('darbul_ansiyyah_darrasah', 'Darbul Ansiyyah Darrasah'), ('bab_zuwaila_darrasah', 'Bab Zuwaila Darrasah'), ('ghurriyah_darrasah', 'Ghurriyah Darrasah'), ('dardir_darrasah', 'Dardir Darrasah'), ('simpang_x_darrasah', 'Simpang X Darrasah'), ('kanisah_darrasah', 'Kanisah Darrasah'), ('belakang_azhar_darrasah', 'Belakang Azhar Darrasah'), ('bab_syariah', "Bab Sya'riah"), ('muqattam', 'Muqattam')], max_length=50, verbose_name='Distrik'),
        ),
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.CharField(blank=True, choices=[('al_azhar', 'Al-Azhar University'), ('mahad_al_azhar', "Ma'had Al Azhar"), ('markaz_zayed', 'Markaz Syeikh Zayed'), ('dirasah_khassah', 'Dirasah Khassah (Markaz Tatwir)'), ('other', 'Lainnya (Isi Sendiri)')], max_length=50, verbose_name='Institusi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='latest_grade',
            field=models.CharField(blank=True, choices=[('mumtaz', 'Mumtaz'), ('jayyid_jiddan', 'Jayyid Jiddan'), ('jayyid', 'Jayyid'), ('maqbul', 'Maqbul'), ('manqul', 'Manqul'), ('manqulain', 'Manqulain'), ('rosib', 'Rosib')], default='', max_length=20, verbose_name='Nilai Terakhir'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='living_cost',
            field=models.CharField(blank=True, choices=[('lt_1jt', '< 1 Jt'), ('1_2jt', '1-2 Jt'), ('2_3jt', '2-3 Jt'), ('gt_3jt', '> 3 Jt')], default='', max_length=20, verbose_name='Biaya Hidup Bulanan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(blank=True, choices=[('adab_naqd', 'Adab wa Naqd'), ('akuntansi', 'Akuntansi'), ('aqidah', 'Aqidah'), ('balaghah_naqd', 'Balaghah wa Naqd'), ('dakwah', 'Dakwah'), ('fiqh_aam', 'Fiqh Aam'), ('fiqh_muqaran', 'Fiqh Muqaran'), ('hadis', 'Hadis'), ('ilmu_quran', 'Ilmu Alquran'), ('ilmu_nafs', 'Ilmu Nafs'), ('kedokteran_gigi', 'Kedokteran Gigi'), ('kedokteran_umum', 'Kedokteran Umum'), ('lughah_almaniyyah', 'Lughah Almaniyyah'), ('lughah_arabiyyah', 'Lughah Arabiyyah'), ('riyadhah', 'Riyadhah'), ('shahafah_ilam', 'Shahafah wa Ilam'), ('syariah_islamiyyah', 'Syariah Islamiyyah'), ('syariah_qanun', 'Syariah wa Qanun'), ('tafsir', 'Tafsir'), ('tarikh', 'Tarikh'), ('tarikh_hadharah', 'Tarikh wa Hadharah'), ('umum', 'Umum'), ('ushul_fiqh', 'Ushul Fiqh'), ('ushul_lughah', 'Ushul Lughah'), ('other', 'Lainnya')], max_length=50, verbose_name='Jurusan'),
        ),
        migrations.AlterField(
            model_name='student',
            name='monthly_income',
            field=models.CharField(blank=True, choices=[('lt_1jt', '< 1 Jt'), ('1_2jt', '1-2 Jt'), ('2_3jt', '2-3 Jt'), ('gt_3jt', '> 3 Jt')], default='', max_length=20, verbose_name='Pendapatan Bulanan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='scholarship_source',
            field=models.CharField(blank=True, choices=[('buuts_dakhili', 'Beasiswa Buuts Dakhili'), ('buuts_khariji', 'Beasiswa Buuts Khariji'), ('majlis_ala', "Beasiswa Majlis A'la"), ('baznas', 'Beasiswa Baznas'), ('asfa', 'Beasiswa ASFA'), ('bait_zakat_kuwait', 'Beasiswa Bait Zakat Kuwait'), ('other', 'Isi Sendiri')], max_length=50, verbose_name='Sumber Beasiswa'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_origin',
            field=models.CharField(blank=True, choices=[('mahad_azhar_mesir', "Ma'had Al-Azhar Mesir"), ('sma_it_insan_cendekia', 'SMA IT Insan Cendekia'), ('ma_ar_risalah', 'MA Ar-Risalah'), ('man_2_padang_panjang', 'MAN 2 kota Padang Panjang'), ('ma_sumatera_thawalib', 'MA Sumatera Thawalib Parabek'), ('ponpes_diniyah_limo_jurai', 'PonPes Diniyah Limo Jurai'), ('ppm_diniyah_pasia', 'PPM Diniyah Pasia'), ('ma_daarul_muwahhidiin', 'MA Daarul Muwahhidiin'), ('pptq_muallimin', 'PPTQ Muallimin Muhammadiyah Sawah Dangka'), ('thawalib_putera', 'Perguruan Thawalib Putera Padang Panjang'), ('mas_kmi_diniyyah', 'MAS KMI Diniyyah Putri'), ('man_2_padang', 'MAN 2 Kota Padang'), ('man_2_payakumbuh', 'MAN 2 Kota Payakumbuh'), ('man_3_padang_panjang', 'MAN 3 Kota Padang Panjang'), ('man_2_tanah_datar', 'MAN 2 Tanah Datar'), ('man_3_tanah_datar', 'MAN 3 Tanah Datar'), ('man_1_bukittinggi', 'MAN 1 Bukittinggi'), ('man_2_bukittinggi', 'MAN 2 Bukittinggi'), ('man_1_solok_selatan', 'MAN 1 Solok Selatan'), ('man_1_pasaman', 'MAN 1 Pasaman'), ('man_5_pasaman_barat', 'MAN 5 Pasaman Barat'), ('ponpes_nurul_yaqin', 'PonPes Nurul Yaqin Ringan-Ringan'), ('mti_canduang', 'MTI Canduang'), ('ppm_darussalam_gontor', 'PPM Darussalam Gontor'), ('baiturridhwan', "Bai'turridhwan Bukittinggi"), ('darul_ulum_lintau', 'Pesantren Darul Ulum Lintau'), ('darul_ulum_padang', 'Pesantren Darul Ulum Padang'), ('yarsi', 'Yarsi'), ('ma_jabal_rahmah', 'MA Jabal Rahmah'), ('sma_darul_amal', 'SMA Terpadu Darul Amal'), ('ponpes_ashabul_yamin', 'Ponpes Ashabul Yamin'), ('mas_taman_raya', 'MAS Taman Raya Balingja'), ('ponpes_madinah_hijrah', 'Ponpes Madinah Al-Hijrah'), ('ma_al_ikhwan', 'MA Al-Ikhwan'), ('pptq_khatib_minangkabawi', 'PPTQ Syech Ahmad Khatib Al-Minangkabawi'), ('sma_adzkia', 'SMA Adzkia'), ('ponpes_kauman', 'PonPes Kauman Muhammadiyah Padang Panjang'), ('man_1_solok', 'MAN 1 Solok'), ('sman_1_payakumbuh', 'SMAN 1 Payakumbuh'), ('mahad_al_hufaz', "Ma'had Al-Hufaz"), ('mas_ppi_haji_miskin', 'MAS PPI Haji Miskin'), ('ma_st_guguak_randah', 'MA ST Guguak Randah'), ('ponpes_istiqamah', 'PonPes Istiqamah Ombilin'), ('mti_djamil_jaho', 'MTI Syeikh Muhammad Djamil Jaho'), ('ponpes_hamka', 'PonPes Prof Dr Hamka Maninjau'), ('mas_ti_lubeg', 'MAS TI Lubeg Padang'), ('sma_dian_andalas', 'SMA Dian Andalas Padang'), ('pp_thawalib_batusangkar', 'PP Thawalib Tanjung Limau Batusangkar'), ('ponpes_abi_center', 'Ponpes Abi Center')], max_length=100, verbose_name='Asal Sekolah'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester_level',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('tamhidi_1', 'Tamhidi 1'), ('tamhidi_2', 'Tamhidi 2'), ('magister', 'Magister'), ('doktoral', 'Doktoral')], max_length=20, verbose_name='Tingkat'),
        ),
    ]
