# Generated by Django 5.2.4 on 2026-03-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0023_categorize_student_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nama Distrik')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Distrik',
                'verbose_name_plural': 'Distrik',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nama Sumber Beasiswa')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sumber Beasiswa',
                'verbose_name_plural': 'Sumber Beasiswa',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nama Sekolah')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Asal Sekolah',
                'verbose_name_plural': 'Asal Sekolah',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='scholarship_source_custom',
        ),
        migrations.AlterField(
            model_name='student',
            name='home_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.district', verbose_name='Distrik'),
        ),
        migrations.AlterField(
            model_name='student',
            name='scholarship_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.scholarshipsource', verbose_name='Sumber Beasiswa'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.schoolorigin', verbose_name='Asal Sekolah'),
        ),
    ]
