# Generated by Django 5.2.4 on 2026-06-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0028_fix_student_field_verbose_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nik',
        ),
    ]
