# Generated by Django 5.2.4 on 2026-06-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0029_remove_nik_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="student_photos/", verbose_name="Foto Profil"
            ),
        ),
    ]
